## ── Waybar ────────────────────────────────────────────────────────────────────
## Status bar with dual CSS modes (rounded pill / square flat).
## Custom modules: GPU stats, CPU temp, network speed.
## CSS is dynamically regenerated by apply-accent (see scripts.nix).
## Remove this import from desktop/default.nix to disable.
{ ... }:

{
	programs.waybar = {
		enable = true;

		settings = {
			mainBar = {
				layer = "top";
				position = "top";
				height = 36;
				spacing = 0;
				exclusive = true;
				ipc = true;

				modules-left = [ "hyprland/workspaces" "hyprland/window" ];
				modules-center = [ "clock" ];
				modules-right = [
					"custom/gpu"
					"cpu"
					"custom/cputemp"
					"memory"
					"custom/netspeed"
					"pulseaudio"
					"tray"
				];

				# ── Left ──────────────────────────────────────────────
				"hyprland/workspaces" = {
					format = "{id}";
					on-click = "activate";
					sort-by-number = true;
					active-only = false;
				};

				"hyprland/window" = {
					max-length = 40;
					separate-outputs = true;
					format = "  {}";
				};

				# ── Center ────────────────────────────────────────────
				clock = {
					format = "{:%H:%M}";
					format-alt = "{:%a %b %d  %H:%M:%S}";
					tooltip-format = "<tt><small>{calendar}</small></tt>";
					interval = 1;
				};

				# ── Right ─────────────────────────────────────────────
				"custom/gpu" = {
					exec = "waybar-gpu";
					return-type = "json";
					interval = 3;
					tooltip = true;
				};

				"custom/cputemp" = {
					exec = "waybar-cputemp";
					return-type = "json";
					interval = 3;
				};

				cpu = {
					format = "[CPU {usage}%";
					interval = 2;
					tooltip = false;
				};

				memory = {
					format = "[MEM {percentage}%]";
					tooltip-format = "RAM: {used:0.1f}G / {total:0.1f}G\nSwap: {swapUsed:0.1f}G / {swapTotal:0.1f}G";
					interval = 5;
				};

				"custom/netspeed" = {
					exec = "waybar-netspeed";
					return-type = "json";
					interval = 2;
				};

				pulseaudio = {
					format = "[VOL {volume}%]";
					format-muted = "[VOL muted]";
					on-click = "wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle";
					scroll-step = 5;
					tooltip-format = "{desc}";
				};

				tray = {
					spacing = 8;
					icon-size = 16;
				};
			};
		};

	};

	# ── CSS managed outside home-manager (toggle-theme swaps at runtime) ─
	xdg.configFile."waybar/style-rounded.css".source = ./style-rounded.css;
	xdg.configFile."waybar/style-square.css".source = ./style-square.css;
	xdg.configFile."waybar/style.css".source = ./style-rounded.css;
}
