## ── Waybar ────────────────────────────────────────────────────────────────────
## Status bar with hover-reveal animations for performance metrics.
## Compact icons by default, expands on hover with smooth transitions.
##
## CSS lifecycle:
##   templates/{rounded,square}.css.tmpl  -- Nix-deployed, immutable
##   ~/.config/waybar/style.css           -- written ONLY by apply-accent
##
## Lifecycle is managed via systemctl --user (see scripts/apply-accent.py).
{ config, lib, ... }:

{
	programs.waybar = {
		enable = true;
		systemd.enable = true;

		settings = {
			mainBar = {
				layer = "top";
				position = "top";
				height = 36;
				spacing = 0;
				exclusive = true;
				ipc = true;

				modules-left = [ "hyprland/workspaces" "hyprland/window" ];
				modules-center = [ "clock" ];
				modules-right = [
					"custom/gpu"
					"custom/cpu"
					"custom/cputemp"
					"memory"
					"custom/netspeed"
					"pulseaudio"
					"tray"
				];

				# ── Left ──────────────────────────────────────────────
				"hyprland/workspaces" = {
					format = "{id}";
					on-click = "activate";
					sort-by-number = true;
					active-only = false;
				};

				"hyprland/window" = {
					max-length = 40;
					separate-outputs = true;
					format = "  {}";
				};

				# ── Center ────────────────────────────────────────────
				clock = {
					format = "{:%H:%M}";
					format-alt = "{:%a %b %d  %H:%M:%S}";
					tooltip-format = "<tt><small>{calendar}</small></tt>";
					interval = 1;
				};

				# ── Right ─────────────────────────────────────────────
				"custom/gpu" = {
					exec = "waybar-gpu";
					return-type = "json";
					interval = 3;
					tooltip = true;
				};

				"custom/cputemp" = {
					exec = "waybar-cputemp";
					return-type = "json";
					interval = 3;
				};

				"custom/cpu" = {
					exec = "waybar-cpu";
					return-type = "json";
					interval = 3;
					tooltip = true;
				};

				memory = {
					format = "󰍛 {percentage}%";
					tooltip-format = "RAM: {used:0.1f}G / {total:0.1f}G\nSwap: {swapUsed:0.1f}G / {swapTotal:0.1f}G";
					interval = 5;
				};

				"custom/netspeed" = {
					exec = "waybar-netspeed";
					return-type = "json";
					interval = 2;
				};

				pulseaudio = {
					format = "󰕾 {volume}%";
					format-muted = "󰖁 muted";
					on-click = "wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle";
					scroll-step = 5;
					tooltip-format = "{desc}";
				};

				tray = {
					spacing = 8;
					icon-size = 16;
				};
			};
		};
	};

	# ── Templates: regenerated by apply-accent into ~/.config/waybar/style.css ─
	xdg.configFile = {
		"waybar/templates/rounded.css.tmpl".source = ./templates/rounded.css.tmpl;
		"waybar/templates/square.css.tmpl".source = ./templates/square.css.tmpl;
	};

	# ── Refresh style.css on every activation (nh os switch) ───────────────
	# Otherwise waybar restarts against a stale style.css and fails to parse
	# it. apply-accent's hyprctl/systemctl calls fail silently if there's no
	# session, but the CSS gets written either way.
	# Also removes legacy style-{rounded,square}.css written by the old code.
	home.activation.refreshWaybarTheme = lib.hm.dag.entryAfter [ "linkGeneration" ] ''
		rm -f "$HOME/.config/waybar/style-rounded.css" "$HOME/.config/waybar/style-square.css"
		${config.home.profileDirectory}/bin/apply-accent >/dev/null 2>&1 || true
	'';
}
