## ── Waybar ────────────────────────────────────────────────────────────────────
## Status bar with hover-reveal animations for performance metrics.
## Compact icons by default, expands on hover with smooth transitions.
## CSS is dynamically regenerated by apply-accent (see scripts.nix).
{ ... }:

{
	programs.waybar = {
		enable = true;

		settings = {
			mainBar = {
				layer = "top";
				position = "top";
				height = 36;
				spacing = 0;
				exclusive = true;
				ipc = true;

				modules-left = [ "hyprland/workspaces" "hyprland/window" ];
				modules-center = [ "clock" ];
				modules-right = [
					"custom/gpu"
					"custom/cpu"
					"custom/cputemp"
					"memory"
					"custom/netspeed"
					"pulseaudio"
					"tray"
				];

				# ── Left ──────────────────────────────────────────────
				"hyprland/workspaces" = {
					format = "{id}";
					on-click = "activate";
					sort-by-number = true;
					active-only = false;
				};

				"hyprland/window" = {
					max-length = 40;
					separate-outputs = true;
					format = "  {}";
				};

				# ── Center ────────────────────────────────────────────
				clock = {
					format = "{:%H:%M}";
					format-alt = "{:%a %b %d  %H:%M:%S}";
					tooltip-format = "<tt><small>{calendar}</small></tt>";
					interval = 1;
				};

				# ── Right ─────────────────────────────────────────────
				"custom/gpu" = {
					exec = "waybar-gpu";
					return-type = "json";
					interval = 3;
					tooltip = true;
				};

				"custom/cputemp" = {
					exec = "waybar-cputemp";
					return-type = "json";
					interval = 3;
				};

				"custom/cpu" = {
					exec = "waybar-cpu";
					return-type = "json";
					interval = 3;
					tooltip = true;
				};

				memory = {
					format = "󰍛 {percentage}%";
					tooltip-format = "RAM: {used:0.1f}G / {total:0.1f}G\nSwap: {swapUsed:0.1f}G / {swapTotal:0.1f}G";
					interval = 5;
				};

				"custom/netspeed" = {
					exec = "waybar-netspeed";
					return-type = "json";
					interval = 2;
				};

				pulseaudio = {
					format = "󰕾 {volume}%";
					format-muted = "󰖁 muted";
					on-click = "wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle";
					scroll-step = 5;
					tooltip-format = "{desc}";
				};

				tray = {
					spacing = 8;
					icon-size = 16;
				};
			};
		};

	};

	# ── CSS deployed as mutable copies (not symlinks) so apply-accent ────
	# and toggle-theme can regenerate them at runtime.
	home.activation.deployWaybarCss = ''
		CSS_SRC="${./style-rounded.css}"
		CSS_SQ="${./style-square.css}"
		DEST="$HOME/.config/waybar"

		mkdir -p "$DEST"

		# Always refresh the base templates
		rm -f "$DEST/style-rounded.css" "$DEST/style-square.css"
		cp "$CSS_SRC" "$DEST/style-rounded.css"
		cp "$CSS_SQ" "$DEST/style-square.css"
		chmod u+w "$DEST/style-rounded.css" "$DEST/style-square.css"

		# Always refresh style.css to match the latest template
		rm -f "$DEST/style.css"
		cp "$CSS_SRC" "$DEST/style.css"
		chmod u+w "$DEST/style.css"
	'';
}
