## ── Btop ──────────────────────────────────────────────────────────────────────
## System monitor with vim keybindings.
## Uses the dynamic "wallpaper" theme generated by apply-accent.
## Remove this import from cli/default.nix to disable.
{ ... }:

{
	programs.btop = {
		enable = true;
		settings = {
			color_theme = "wallpaper";
			vim_keys = true;
		};
	};
}
